# shortener/tests.py
from django.test import TestCase
from django.urls import reverse
from rest_framework import status
from rest_framework.test import APITestCase
from .models import URL
from analytics.models import ClickAnalytics

class URLShortenerTests(APITestCase):

    def test_home_page_renders(self):
        """
        Ensures the landing page is available to visitors.
        """
        response = self.client.get(reverse('home'))

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertContains(response, 'URL Shortener')
        self.assertContains(response, 'Paste your long URL')

    def test_analytics_report_page_renders(self):
        """
        Ensures the full analytics report page is accessible.
        """
        response = self.client.get(reverse('analytics_report'))

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertContains(response, 'Analytics Report')

    def test_root_report_redirect(self):
        """
        Ensures the top-level report URL redirects to the app report page.
        """
        response = self.client.get('/analytics-report/')

        self.assertEqual(response.status_code, 302)
        self.assertEqual(response['Location'], '/shortener/analytics-report/')
    
    def setUp(self):
        """
        Runs automatically before every single test.
        Creates a dummy URL record to test redirects and metrics.
        """
        self.long_url = "https://www.python.org"
        self.url_instance = URL.objects.create(long_url=self.long_url)
        # Note: The short_code is auto-generated by our pre_save signal!

    def test_url_creation_via_api(self):
        """
        Ensures a POST request to the API cleanly generates a shortened asset.
        """
        url = reverse('api_url_create')
        data = {"long_url": "https://www.django-rest-framework.org"}
        
        response = self.client.post(url, data, format='json')
        
        # Check if status code is 201 Created
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        # Check if a unique short code was actually returned
        self.assertIn('short_code', response.data) # type: ignore
        self.assertTrue(len(response.data['short_code']) == 6) # type: ignore

    def test_redirection_flow(self):
        """
        Ensures hitting a short link yields a proper HTTP 302 redirect 
        pointing straight to the original destination website.
        """
        url = reverse('url_redirect', kwargs={'short_code': self.url_instance.short_code})
        
        response = self.client.get(url)
        
        # Verify it returns a 302 Found Redirect
        self.assertEqual(response.status_code, 302)
        # Verify the Location header points to our exact destination link
        self.assertEqual(response['Location'], self.long_url)

    def test_analytics_logging(self):
        """
        Ensures every redirect execution records accurate metric logs.
        """
        url = reverse('url_redirect', kwargs={'short_code': self.url_instance.short_code})
        
        # Simulate an Edge browser click
        edge_user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0"
        self.client.get(url, HTTP_USER_AGENT=edge_user_agent, HTTP_REFERER="https://github.com")
        
        # Verify a click log was written into our analytics database
        analytics_count = ClickAnalytics.objects.filter(url=self.url_instance).count()
        self.assertEqual(analytics_count, 1)
        
        # Verify the Edge and Referrer properties matched perfectly
        log = ClickAnalytics.objects.filter(url=self.url_instance).first()
        self.assertEqual(log.browser, "Edge") # type: ignore
        self.assertEqual(log.referrer, "github.com") # type: ignore

    def test_swagger_docs_are_available(self):
        """
        Ensures the Swagger documentation endpoint is reachable.
        """
        response = self.client.get(reverse('schema-swagger-ui'))

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertContains(response, 'swagger')

    def test_analytics_api_endpoint(self):
        """
        Ensures the analytics endpoint returns structured telemetry JSON.
        """
        # Trigger 1 click event to populate data
        url_redirect = reverse('url_redirect', kwargs={'short_code': self.url_instance.short_code})
        self.client.get(url_redirect)
        
        # Hit the metrics dashboard endpoint
        url_analytics = reverse('api_url_analytics', kwargs={'short_code': self.url_instance.short_code})
        response = self.client.get(url_analytics)
        
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(response.data['total_clicks'], 1) # type: ignore
        self.assertIn('browsers', response.data['metrics']) # type: ignore