# Generated by Django 6.0.6 on 2026-06-19 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('browser', models.CharField(blank=True, default='Unknown', max_length=100, null=True)),
                ('device_type', models.CharField(blank=True, default='Unknown', max_length=50, null=True)),
                ('referrer', models.CharField(blank=True, default='Direct', max_length=255, null=True)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='shortener.url')),
            ],
            options={
                'verbose_name_plural': 'Click Analytics',
                'ordering': ['-clicked_at'],
            },
        ),
    ]
